name: basit_workspace
on: [push]
jobs:
  basit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy static files to AWS S3
        id: aws-deploy-s3
        uses: oneyedev/aws-deploy-s3@v2
        with:
          region: us-east-1
          bucket: githubactiondeploy456
          source: ./
          target: arn:aws:s3:::githubactiondeploy456